import { createServerClient } from "@supabase/ssr";
import { NextResponse, type NextRequest } from "next/server";

import { isProfileDataComplete } from "@/lib/profile-completeness";

// Reachable with no session at all — the Strava OAuth entry/callback (the
// only login flow this app has) and the login screen itself. `/auth/callback`
// is the dual-logo transition page Strava redirects back to (see
// `getStravaRedirectUri` in `lib/strava.ts`) — there's no session yet at that
// point either, since it's what forwards into `/api/auth/strava/callback`
// to actually establish one. `/privacidad` also has to be public — Strava's
// API Agreement requires a published privacy policy reachable *before* a
// visitor connects their account, not only after logging in. `/robots.txt`/
// `/sitemap.xml` (generated by `app/robots.ts`/`app/sitemap.ts`) must be public
// too — a search-engine crawler never has a session, so without this they'd
// silently 307 to `/login` instead of ever reaching the actual file, which
// would make both files unreachable to the one audience they're for. Everything
// else requires a real signed-in user.
const PUBLIC_PATH_PREFIXES = [
  "/login",
  "/auth/callback",
  "/privacidad",
  "/robots.txt",
  "/sitemap.xml",
  "/api/strava/connect",
  "/api/auth/strava/callback",
];

function isPublicPath(pathname: string): boolean {
  return PUBLIC_PATH_PREFIXES.some((prefix) => pathname.startsWith(prefix));
}

/**
 * Refreshes the Supabase session on every request (per Supabase's standard
 * Next.js SSR pattern) and gates every non-public route behind it — this is
 * what makes "Conectar con Strava" a real login rather than cosmetic UI,
 * since without this a stale/expired session would silently keep serving
 * pages instead of bouncing back to `/login`. `supabase.auth.getUser()` is
 * used rather than `getSession()` because it revalidates the JWT against
 * Supabase's server instead of trusting whatever the cookie claims.
 */
export async function proxy(request: NextRequest) {
  let response = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          response = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, options)
          );
        },
      },
    }
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();

  const { pathname } = request.nextUrl;

  if (!user && !isPublicPath(pathname)) {
    const url = request.nextUrl.clone();
    url.pathname = "/login";
    return NextResponse.redirect(url);
  }

  if (user && pathname === "/login") {
    const url = request.nextUrl.clone();
    url.pathname = "/";
    return NextResponse.redirect(url);
  }

  // Mandatory profile completion: an athlete with no usable Physiological
  // Profile can't reach the Dashboard/Estadísticas/Historial at all — every
  // one of those relies on real weight/FTP/sweat-rate/gut-training data, so
  // rather than each page rendering its own "perfil incompleto" blocked
  // state (the previous design), the guard now lives here, once, and simply
  // never lets an incomplete profile past `/perfil` in the first place. Only
  // `/perfil` itself is exempt (that's where they complete it) — API routes
  // are exempt too, since they already return their own `{ error: "no_profile" }`
  // JSON on an incomplete profile (see `app/api/fueling/plan/route.ts` and
  // `app/api/post-ride/analysis/route.ts`), and a middleware redirect to an
  // HTML page would silently break whatever `fetch()` call expected JSON
  // back. Public paths are already handled above (a null `user` there just
  // bounces to `/login`, so this only ever runs for a real signed-in user).
  if (user && pathname !== "/perfil" && !pathname.startsWith("/api") && !isPublicPath(pathname)) {
    const { data: profileRow } = await supabase
      .from("athlete_profiles")
      .select("weight_kg, ftp, gut_training_level, sweat_rate")
      .eq("id", user.id)
      .maybeSingle();

    if (!isProfileDataComplete(profileRow)) {
      const url = request.nextUrl.clone();
      url.pathname = "/perfil";
      return NextResponse.redirect(url);
    }
  }

  return response;
}

export const config = {
  matcher: ["/((?!_next/static|_next/image|favicon.ico|apple-icon|icon|manifest.webmanifest).*)"],
};
